// Auto-generated High-Availability Dataset for Cooperator Partner Hubs & Corridors
export const FACTORY_OPERATORS = [
  {
    "id": "hub-8star",
    "name": "[8 Star] Phnom Penh Logistics Hub",
    "code": "8STAR-101",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/pdjF6ZVyfeCBxqno9",
    "latitude": 11.5256759,
    "longitude": 104.8719561,
    "contact_phone": "+855 12 888 777",
    "manager_name": "8 Star Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-hongsone",
    "name": "[Hongs One] Phnom Penh Logistics Hub",
    "code": "HONGSO-106",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/hbFRJb63rdP9tssAA",
    "latitude": 11.5216358,
    "longitude": 104.8592455,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Hongs One Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-kkn",
    "name": "[KKN Apparel] Koh Kong Logistics Hub",
    "code": "KKN-111",
    "province": "Koh Kong",
    "address": "https://maps.app.goo.gl/W5V6GqY1R25MpX5F8",
    "latitude": 11.6485424,
    "longitude": 102.933553,
    "contact_phone": "+855 12 888 777",
    "manager_name": "KKN Apparel Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-powergrown",
    "name": "[Power Grown] Kampong Speu Logistics Hub",
    "code": "POWERG-116",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/KaRSJwoUDx2H7Bfa7",
    "latitude": 11.5246115,
    "longitude": 104.7663945,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Power Grown Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-starlight",
    "name": "[Starlight] Kandal Logistics Hub",
    "code": "STARLI-121",
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/TBs99m7FeiJbi4SJ6",
    "latitude": 11.6830335,
    "longitude": 105.0396844,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Starlight Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-texson",
    "name": "[Texson] Kampong Speu Logistics Hub",
    "code": "TEXSON-126",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/uAzxTATfZZQ7XPdH7",
    "latitude": 11.4107486,
    "longitude": 104.778564,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Texson Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-yakjin",
    "name": "[Yakjin] Kampong Speu Logistics Hub",
    "code": "YAKJIN-131",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/og6r54WjxAqe33TGA",
    "latitude": 11.5280607,
    "longitude": 104.7761474,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Yakjin Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-bowker",
    "name": "[Bowker] Phnom Penh Logistics Hub",
    "code": "BOWKER-102",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/tRde6E834dmeitt3A",
    "latitude": 11.53399,
    "longitude": 104.82673,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Bowker Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-hungwah",
    "name": "[Hung Wah] Phnom Penh Logistics Hub",
    "code": "HUNGWA-107",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/XzCHsB5mCg414rKf9",
    "latitude": 11.532625,
    "longitude": 104.8546699,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Hung Wah Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-makalot",
    "name": "[Makalot] Phnom Penh Logistics Hub",
    "code": "MAKALO-112",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/VpprSqQEfTPfLv8h6",
    "latitude": 11.53011,
    "longitude": 104.87208,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Makalot Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-rongwin",
    "name": "[Rong Win] Phnom Penh Logistics Hub",
    "code": "RONGWI-117",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/1rvUmVq55aoVevNbA",
    "latitude": 11.5248737,
    "longitude": 104.8642954,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Rong Win Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-sunhsu",
    "name": "[SunHsu] Kampong Cham Logistics Hub",
    "code": "SUNHSU-122",
    "province": "Kampong Cham",
    "address": "https://maps.app.goo.gl/tP6szikGizA1J5Vq7",
    "latitude": 12.0597978,
    "longitude": 105.209486,
    "contact_phone": "+855 12 888 777",
    "manager_name": "SunHsu Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-topsummit",
    "name": "[Top Summit] Kampong Speu Logistics Hub",
    "code": "TOPSUM-127",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/jPbYu72Tue2zFZ23A",
    "latitude": 11.5253486,
    "longitude": 104.7934172,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Top Summit Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-ytc",
    "name": "[YTC] Kampong Speu Logistics Hub",
    "code": "YTC-132",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/B9dWFZGgEzQodtFbA",
    "latitude": 11.4734344,
    "longitude": 104.5797424,
    "contact_phone": "+855 12 888 777",
    "manager_name": "YTC Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-elite",
    "name": "[Elite] Svay Rieng Logistics Hub",
    "code": "ELITE-103",
    "province": "Svay Rieng",
    "address": "https://maps.app.goo.gl/mg3uV9gY4hxjurpS8",
    "latitude": 11.048127,
    "longitude": 106.1194589,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Elite Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-injae",
    "name": "[In Jae] Phnom Penh Logistics Hub",
    "code": "INJAE-108",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/kyfwoFQ67SKLGLtp7",
    "latitude": 11.5984166,
    "longitude": 104.9029546,
    "contact_phone": "+855 12 888 777",
    "manager_name": "In Jae Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-moha",
    "name": "[Moha Garments] Kandal Logistics Hub",
    "code": "MOHA-113",
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/FQF1rywJfkfWr49QA",
    "latitude": 11.453196,
    "longitude": 104.8064468,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Moha Garments Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-seduno",
    "name": "[Seduno] Phnom Penh Logistics Hub",
    "code": "SEDUNO-118",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/NzjCrLQeWGiGSikWA",
    "latitude": 11.5054537,
    "longitude": 104.8937039,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Seduno Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-sunfair",
    "name": "[Sunfair] Kampong Speu Logistics Hub",
    "code": "SUNFAI-123",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/YzWQcm2UhBc8QaTs8",
    "latitude": 11.4524278,
    "longitude": 104.7742024,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Sunfair Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-trax",
    "name": "[Trax Apparel] Phnom Penh Logistics Hub",
    "code": "TRAX-128",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/ZEnjGqHi73HZ5Bnb6",
    "latitude": 11.5613297,
    "longitude": 104.8756385,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Trax Apparel Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-eminent",
    "name": "[Eminent] Kandal Logistics Hub",
    "code": "EMINEN-104",
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/J4BqshSy2RbY5Gtq5",
    "latitude": 11.3325125,
    "longitude": 105.0326094,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Eminent Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-jointforce",
    "name": "[Joint Force] Phnom Penh Logistics Hub",
    "code": "JOINTF-109",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/35HtJ81Rmhrg5XGZ6",
    "latitude": 11.5254809,
    "longitude": 104.8298356,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Joint Force Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-nyankids",
    "name": "[Nyan Kids] Kampong Speu Logistics Hub",
    "code": "NYANKI-114",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/PHXKcF3qv687CatFA",
    "latitude": 11.5216599,
    "longitude": 104.7786931,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Nyan Kids Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-sixplus",
    "name": "[Sixplus] Kandal Logistics Hub",
    "code": "SIXPLU-119",
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/dfFWQxaxuxWHaz5B8",
    "latitude": 11.7415371,
    "longitude": 104.9820076,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Sixplus Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-tlhandbags",
    "name": "[T&L Handbags] Kampong Speu Logistics Hub",
    "code": "TLHAND-124",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/dmU3LCdJba1EAGxq5",
    "latitude": 11.5390701,
    "longitude": 104.7778396,
    "contact_phone": "+855 12 888 777",
    "manager_name": "T&L Handbags Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-wanheda",
    "name": "[Wan He Da] Kampong Speu Logistics Hub",
    "code": "WANHED-129",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/2syua7ePP4Y7Gp766",
    "latitude": 11.5274694,
    "longitude": 104.7987984,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Wan He Da Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-fortuna",
    "name": "[Fortuna] Phnom Penh Logistics Hub",
    "code": "FORTUN-105",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/JFWsmQJKXA846B6s6",
    "latitude": 11.5289942,
    "longitude": 104.8547169,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Fortuna Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-kingsuccess",
    "name": "[King Success] Kandal Logistics Hub",
    "code": "KINGSU-110",
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/nxM9M1VG9wipMcTH7",
    "latitude": 11.4552078,
    "longitude": 104.991836,
    "contact_phone": "+855 12 888 777",
    "manager_name": "King Success Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-ocean",
    "name": "[Ocean Apparel] Kampong Speu Logistics Hub",
    "code": "OCEAN-115",
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/8bsem3Vx9y4ysauD8",
    "latitude": 11.5292663,
    "longitude": 104.793456,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Ocean Apparel Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-skyworth",
    "name": "[Skyworth] Phnom Penh Logistics Hub",
    "code": "SKYWOR-120",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/BHnfNw2KeqY2RPuX9",
    "latitude": 11.5318879,
    "longitude": 104.8779362,
    "contact_phone": "+855 12 888 777",
    "manager_name": "Skyworth Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-tfg",
    "name": "[T.F.G] Kampong Chhnang Logistics Hub",
    "code": "TFG-125",
    "province": "Kampong Chhnang",
    "address": "https://maps.app.goo.gl/U5p7apvExhcHRZN68",
    "latitude": 11.8886181,
    "longitude": 104.7098528,
    "contact_phone": "+855 12 888 777",
    "manager_name": "T.F.G Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  },
  {
    "id": "hub-xotex",
    "name": "[XO TEX] Phnom Penh Logistics Hub",
    "code": "XOTEX-130",
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/sE6hoX4r3W2zBq6A8",
    "latitude": 11.5282947,
    "longitude": 104.8646301,
    "contact_phone": "+855 12 888 777",
    "manager_name": "XO TEX Dispatch Operations",
    "manager_phone": "+855 12 888 123",
    "operating_hours": "24/7 Gate Dispatch",
    "loading_bays": 8,
    "weighbridge_capacity": "80 Tons Axle Scale",
    "fleet_count": 2,
    "rating": 5,
    "status": "active",
    "amenities": [
      "Driver Rest Lounge",
      "Diesel Fuel Pump",
      "24/7 Security"
    ]
  }
];

export const FACTORY_ROUTES = [
  {
    "id": "r-injae",
    "operator_id": "hub-injae",
    "name": "Top Sports HQ ⇄ In Jae (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[In Jae] [In Jae] Phnom Penh Logistics Hub",
    "distance_km": 168.3,
    "duration_hours": 2.4,
    "duration_min": 144,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[In Jae] Factory Loading Bay"
    ]
  },
  {
    "id": "r-moha",
    "operator_id": "hub-moha",
    "name": "Top Sports HQ ⇄ Moha Garments (Kandal)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Moha Garments] [Moha Garments] Kandal Logistics Hub",
    "distance_km": 176.3,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Moha Garments] Factory Loading Bay"
    ]
  },
  {
    "id": "r-seduno",
    "operator_id": "hub-seduno",
    "name": "Top Sports HQ ⇄ Seduno (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Seduno] [Seduno] Phnom Penh Logistics Hub",
    "distance_km": 175.7,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Seduno] Factory Loading Bay"
    ]
  },
  {
    "id": "r-sunfair",
    "operator_id": "hub-sunfair",
    "name": "Top Sports HQ ⇄ Sunfair (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Sunfair] [Sunfair] Kampong Speu Logistics Hub",
    "distance_km": 180.8,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Sunfair] Factory Loading Bay"
    ]
  },
  {
    "id": "r-trax",
    "operator_id": "hub-trax",
    "name": "Top Sports HQ ⇄ Trax Apparel (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Trax Apparel] [Trax Apparel] Phnom Penh Logistics Hub",
    "distance_km": 169.9,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Trax Apparel] Factory Loading Bay"
    ]
  },
  {
    "id": "r-jointforce",
    "operator_id": "hub-jointforce",
    "name": "Top Sports HQ ⇄ Joint Force (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Joint Force] [Joint Force] Phnom Penh Logistics Hub",
    "distance_km": 183.5,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Joint Force] Factory Loading Bay"
    ]
  },
  {
    "id": "r-nyankids",
    "operator_id": "hub-nyankids",
    "name": "Top Sports HQ ⇄ Nyan Kids (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Nyan Kids] [Nyan Kids] Kampong Speu Logistics Hub",
    "distance_km": 188.1,
    "duration_hours": 2.7,
    "duration_min": 162,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Nyan Kids] Factory Loading Bay"
    ]
  },
  {
    "id": "r-sixplus",
    "operator_id": "hub-sixplus",
    "name": "Top Sports HQ ⇄ Sixplus (Kandal)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Sixplus] [Sixplus] Kandal Logistics Hub",
    "distance_km": 186.7,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Sixplus] Factory Loading Bay"
    ]
  },
  {
    "id": "r-kingsuccess",
    "operator_id": "hub-kingsuccess",
    "name": "Top Sports HQ ⇄ King Success (Kandal)",
    "origin": "Top Sports Textile HQ",
    "destination": "[King Success] [King Success] Kandal Logistics Hub",
    "distance_km": 153.7,
    "duration_hours": 2.2,
    "duration_min": 132,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[King Success] Factory Loading Bay"
    ]
  },
  {
    "id": "r-ocean",
    "operator_id": "hub-ocean",
    "name": "Top Sports HQ ⇄ Ocean Apparel (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Ocean Apparel] [Ocean Apparel] Kampong Speu Logistics Hub",
    "distance_km": 186.7,
    "duration_hours": 2.7,
    "duration_min": 162,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Ocean Apparel] Factory Loading Bay"
    ]
  },
  {
    "id": "r-skyworth",
    "operator_id": "hub-skyworth",
    "name": "Top Sports HQ ⇄ Skyworth (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Skyworth] [Skyworth] Phnom Penh Logistics Hub",
    "distance_km": 169.6,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Skyworth] Factory Loading Bay"
    ]
  },
  {
    "id": "r-kkn",
    "operator_id": "hub-kkn",
    "name": "Top Sports HQ ⇄ KKN Apparel (Koh Kong)",
    "origin": "Top Sports Textile HQ",
    "destination": "[KKN Apparel] [KKN Apparel] Koh Kong Logistics Hub",
    "distance_km": 462.3,
    "duration_hours": 6.5,
    "duration_min": 390,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[KKN Apparel] Factory Loading Bay"
    ]
  },
  {
    "id": "r-powergrown",
    "operator_id": "hub-powergrown",
    "name": "Top Sports HQ ⇄ Power Grown (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Power Grown] [Power Grown] Kampong Speu Logistics Hub",
    "distance_km": 190.3,
    "duration_hours": 2.7,
    "duration_min": 162,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Power Grown] Factory Loading Bay"
    ]
  },
  {
    "id": "r-starlight",
    "operator_id": "hub-starlight",
    "name": "Top Sports HQ ⇄ Starlight (Kandal)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Starlight] [Starlight] Kandal Logistics Hub",
    "distance_km": 195.3,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Starlight] Factory Loading Bay"
    ]
  },
  {
    "id": "r-makalot",
    "operator_id": "hub-makalot",
    "name": "Top Sports HQ ⇄ Makalot (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Makalot] [Makalot] Phnom Penh Logistics Hub",
    "distance_km": 169.9,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Makalot] Factory Loading Bay"
    ]
  },
  {
    "id": "r-rongwin",
    "operator_id": "hub-rongwin",
    "name": "Top Sports HQ ⇄ Rong Win (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Rong Win] [Rong Win] Phnom Penh Logistics Hub",
    "distance_km": 171.2,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Rong Win] Factory Loading Bay"
    ]
  },
  {
    "id": "r-sunhsu",
    "operator_id": "hub-sunhsu",
    "name": "Top Sports HQ ⇄ SunHsu (Kampong Cham)",
    "origin": "Top Sports Textile HQ",
    "destination": "[SunHsu] [SunHsu] Kampong Cham Logistics Hub",
    "distance_km": 187.2,
    "duration_hours": 2.7,
    "duration_min": 162,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[SunHsu] Factory Loading Bay"
    ]
  },
  {
    "id": "r-tlhandbags",
    "operator_id": "hub-tlhandbags",
    "name": "Top Sports HQ ⇄ T&L Handbags (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[T&L Handbags] [T&L Handbags] Kampong Speu Logistics Hub",
    "distance_km": 190,
    "duration_hours": 2.7,
    "duration_min": 162,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[T&L Handbags] Factory Loading Bay"
    ]
  },
  {
    "id": "r-wanheda",
    "operator_id": "hub-wanheda",
    "name": "Top Sports HQ ⇄ Wan He Da (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Wan He Da] [Wan He Da] Kampong Speu Logistics Hub",
    "distance_km": 185.7,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Wan He Da] Factory Loading Bay"
    ]
  },
  {
    "id": "r-tfg",
    "operator_id": "hub-tfg",
    "name": "Top Sports HQ ⇄ T.F.G (Kampong Chhnang)",
    "origin": "Top Sports Textile HQ",
    "destination": "[T.F.G] [T.F.G] Kampong Chhnang Logistics Hub",
    "distance_km": 210.9,
    "duration_hours": 2.9,
    "duration_min": 174,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[T.F.G] Factory Loading Bay"
    ]
  },
  {
    "id": "r-xotex",
    "operator_id": "hub-xotex",
    "name": "Top Sports HQ ⇄ XO TEX (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[XO TEX] [XO TEX] Phnom Penh Logistics Hub",
    "distance_km": 170.7,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[XO TEX] Factory Loading Bay"
    ]
  },
  {
    "id": "r-texson",
    "operator_id": "hub-texson",
    "name": "Top Sports HQ ⇄ Texson (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Texson] [Texson] Kampong Speu Logistics Hub",
    "distance_km": 179.8,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Texson] Factory Loading Bay"
    ]
  },
  {
    "id": "r-yakjin",
    "operator_id": "hub-yakjin",
    "name": "Top Sports HQ ⇄ Yakjin (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Yakjin] [Yakjin] Kampong Speu Logistics Hub",
    "distance_km": 189.2,
    "duration_hours": 2.7,
    "duration_min": 162,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Yakjin] Factory Loading Bay"
    ]
  },
  {
    "id": "r-fortuna",
    "operator_id": "hub-fortuna",
    "name": "Top Sports HQ ⇄ Fortuna (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Fortuna] [Fortuna] Phnom Penh Logistics Hub",
    "distance_km": 171.7,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Fortuna] Factory Loading Bay"
    ]
  },
  {
    "id": "r-8star",
    "operator_id": "hub-8star",
    "name": "Top Sports HQ ⇄ 8 Star (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[8 Star] [8 Star] Phnom Penh Logistics Hub",
    "distance_km": 170.3,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[8 Star] Factory Loading Bay"
    ]
  },
  {
    "id": "r-hongsone",
    "operator_id": "hub-hongsone",
    "name": "Top Sports HQ ⇄ Hongs One (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Hongs One] [Hongs One] Phnom Penh Logistics Hub",
    "distance_km": 172,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Hongs One] Factory Loading Bay"
    ]
  },
  {
    "id": "r-bowker",
    "operator_id": "hub-bowker",
    "name": "Top Sports HQ ⇄ Bowker (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Bowker] [Bowker] Phnom Penh Logistics Hub",
    "distance_km": 185.6,
    "duration_hours": 2.6,
    "duration_min": 156,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Bowker] Factory Loading Bay"
    ]
  },
  {
    "id": "r-hungwah",
    "operator_id": "hub-hungwah",
    "name": "Top Sports HQ ⇄ Hung Wah (Phnom Penh)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Hung Wah] [Hung Wah] Phnom Penh Logistics Hub",
    "distance_km": 171.6,
    "duration_hours": 2.5,
    "duration_min": 150,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Hung Wah] Factory Loading Bay"
    ]
  },
  {
    "id": "r-topsummit",
    "operator_id": "hub-topsummit",
    "name": "Top Sports HQ ⇄ Top Summit (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Top Summit] [Top Summit] Kampong Speu Logistics Hub",
    "distance_km": 186.4,
    "duration_hours": 2.7,
    "duration_min": 162,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Top Summit] Factory Loading Bay"
    ]
  },
  {
    "id": "r-ytc",
    "operator_id": "hub-ytc",
    "name": "Top Sports HQ ⇄ YTC (Kampong Speu)",
    "origin": "Top Sports Textile HQ",
    "destination": "[YTC] [YTC] Kampong Speu Logistics Hub",
    "distance_km": 206.6,
    "duration_hours": 2.9,
    "duration_min": 174,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[YTC] Factory Loading Bay"
    ]
  },
  {
    "id": "r-elite",
    "operator_id": "hub-elite",
    "name": "Top Sports HQ ⇄ Elite (Svay Rieng)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Elite] [Elite] Svay Rieng Logistics Hub",
    "distance_km": 0.2,
    "duration_hours": 0.1,
    "duration_min": 5,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "Manhattan SEZ Logistics Gate",
      "[Elite] Factory Loading Bay"
    ]
  },
  {
    "id": "r-eminent",
    "operator_id": "hub-eminent",
    "name": "Top Sports HQ ⇄ Eminent (Kandal)",
    "origin": "Top Sports Textile HQ",
    "destination": "[Eminent] [Eminent] Kandal Logistics Hub",
    "distance_km": 167.8,
    "duration_hours": 2.4,
    "duration_min": 144,
    "status": "active",
    "stops": [
      "Top Sports Textile Central Staging Base",
      "NR1 Neak Loeung Toll Plaza",
      "[Eminent] Factory Loading Bay"
    ]
  }
];

export const FACTORY_COOPERATORS = [
  {
    "id": "cop-eminent",
    "name": "EMINENT GARMENT (CAMBODIA) LIMITED",
    "factory_name": "Eminent Garment (Cambodia) Limited",
    "short_name": "Eminent",
    "code": "COP-EMINENT-04",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/J4BqshSy2RbY5Gtq5",
    "latitude": 11.3325125,
    "longitude": 105.0326094,
    "operator_id": "hub-eminent",
    "hub_name": "[Eminent] Kandal Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Eminent (Kandal)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "EMINENT GARMENT (CAMBODIA) LIMITED • https://maps.app.goo.gl/J4BqshSy2RbY5Gtq5"
  },
  {
    "id": "cop-8star",
    "name": "8 STAR SPORTSWEAR LTD.",
    "factory_name": "រោងចក្រ ៨ស្តារ ស្ពតវែរ អិលធីឌី",
    "short_name": "8 Star",
    "code": "COP-8STAR-01",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/pdjF6ZVyfeCBxqno9",
    "latitude": 11.5256759,
    "longitude": 104.8719561,
    "operator_id": "hub-8star",
    "hub_name": "[8 Star] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ 8 Star (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "8 STAR SPORTSWEAR LTD. • https://maps.app.goo.gl/pdjF6ZVyfeCBxqno9"
  },
  {
    "id": "cop-bowker",
    "name": "BOWKER GARMENT FACTORY (CAMBODIA) COMPANY LIMITED",
    "factory_name": "Bowker Garment Factory (Cambodia) Bek Chan",
    "short_name": "Bowker",
    "code": "COP-BOWKER-02",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/tRde6E834dmeitt3A",
    "latitude": 11.53399,
    "longitude": 104.82673,
    "operator_id": "hub-bowker",
    "hub_name": "[Bowker] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Bowker (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "BOWKER GARMENT FACTORY (CAMBODIA) COMPANY LIMITED • https://maps.app.goo.gl/tRde6E834dmeitt3A"
  },
  {
    "id": "cop-elite",
    "name": "ELITE (CAMBODIA) CO., LTD",
    "factory_name": "ELITE (CAMBODIA) CO., LTD",
    "short_name": "Elite",
    "code": "COP-ELITE-03",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Svay Rieng",
    "address": "https://maps.app.goo.gl/mg3uV9gY4hxjurpS8",
    "latitude": 11.048127,
    "longitude": 106.1194589,
    "operator_id": "hub-elite",
    "hub_name": "[Elite] Svay Rieng Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Elite (Svay Rieng)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "ELITE (CAMBODIA) CO., LTD • https://maps.app.goo.gl/mg3uV9gY4hxjurpS8"
  },
  {
    "id": "cop-powergrown",
    "name": "POWER GROWN FOOTWEAR (CAMBODIA) CO.,LTD",
    "factory_name": "富荣欣鞋业（柬埔寨）有限公司 POWER GROWN FOOTWEAR (CAMBODIA) CO.,LTD",
    "short_name": "Power Grown",
    "code": "COP-POWERGRO-16",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/KaRSJwoUDx2H7Bfa7",
    "latitude": 11.5246115,
    "longitude": 104.7663945,
    "operator_id": "hub-powergrown",
    "hub_name": "[Power Grown] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Power Grown (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "POWER GROWN FOOTWEAR (CAMBODIA) CO.,LTD • https://maps.app.goo.gl/KaRSJwoUDx2H7Bfa7"
  },
  {
    "id": "cop-texson",
    "name": "Texson (Cambodia) Knitting Washing Dyeing & Printing Co., Ltd.",
    "factory_name": "Texson (Cambodia) Knitting Washing Dyeing & Printing Co., Ltd.",
    "short_name": "Texson",
    "code": "COP-TEXSON-26",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/uAzxTATfZZQ7XPdH7",
    "latitude": 11.4107486,
    "longitude": 104.778564,
    "operator_id": "hub-texson",
    "hub_name": "[Texson] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Texson (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Texson (Cambodia) Knitting Washing Dyeing & Printing Co., Ltd. • https://maps.app.goo.gl/uAzxTATfZZQ7XPdH7"
  },
  {
    "id": "cop-hungwah",
    "name": "Hung Wah (Cambodia) Garment MFG. Ltd.",
    "factory_name": "Hung Wah (Cambodia) Garment MFG. Ltd.",
    "short_name": "Hung Wah",
    "code": "COP-HUNGWAH-07",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/XzCHsB5mCg414rKf9",
    "latitude": 11.532625,
    "longitude": 104.8546699,
    "operator_id": "hub-hungwah",
    "hub_name": "[Hung Wah] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Hung Wah (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Hung Wah (Cambodia) Garment MFG. Ltd. • https://maps.app.goo.gl/XzCHsB5mCg414rKf9"
  },
  {
    "id": "cop-rongwin",
    "name": "Rong Win Garment Co., Ltd.",
    "factory_name": "Rong Win Garment Co., Ltd.",
    "short_name": "Rong Win",
    "code": "COP-RONGWIN-17",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/1rvUmVq55aoVevNbA",
    "latitude": 11.5248737,
    "longitude": 104.8642954,
    "operator_id": "hub-rongwin",
    "hub_name": "[Rong Win] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Rong Win (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Rong Win Garment Co., Ltd. • https://maps.app.goo.gl/1rvUmVq55aoVevNbA"
  },
  {
    "id": "cop-injae",
    "name": "IN JAE GARMENT CO., LTD.",
    "factory_name": "INJAE GARMENT",
    "short_name": "In Jae",
    "code": "COP-INJAE-08",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/kyfwoFQ67SKLGLtp7",
    "latitude": 11.5984166,
    "longitude": 104.9029546,
    "operator_id": "hub-injae",
    "hub_name": "[In Jae] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ In Jae (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "IN JAE GARMENT CO., LTD. • https://maps.app.goo.gl/kyfwoFQ67SKLGLtp7"
  },
  {
    "id": "cop-seduno",
    "name": "Seduno Investment Cambo Fashion Co., Ltd.",
    "factory_name": "Seduno Investment Cambo Fashion Co., Ltd.",
    "short_name": "Seduno",
    "code": "COP-SEDUNO-18",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/NzjCrLQeWGiGSikWA",
    "latitude": 11.5054537,
    "longitude": 104.8937039,
    "operator_id": "hub-seduno",
    "hub_name": "[Seduno] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Seduno (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Seduno Investment Cambo Fashion Co., Ltd. • https://maps.app.goo.gl/NzjCrLQeWGiGSikWA"
  },
  {
    "id": "cop-jointforce",
    "name": "JOINT FORCE SPORTING GOODS (CAMBODIA) CO., LTD.",
    "factory_name": "JOINT FORCE SPORTING GOODS (CAMBODIA) CO., LTD.",
    "short_name": "Joint Force",
    "code": "COP-JOINTFOR-09",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/35HtJ81Rmhrg5XGZ6",
    "latitude": 11.5254809,
    "longitude": 104.8298356,
    "operator_id": "hub-jointforce",
    "hub_name": "[Joint Force] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Joint Force (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "JOINT FORCE SPORTING GOODS (CAMBODIA) CO., LTD. • https://maps.app.goo.gl/35HtJ81Rmhrg5XGZ6"
  },
  {
    "id": "cop-sixplus",
    "name": "SIXPLUS INDUSTRY CO., LTD.",
    "factory_name": "SIXPLUS INDUSTRY CO., LTD.",
    "short_name": "Sixplus",
    "code": "COP-SIXPLUS-19",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/dfFWQxaxuxWHaz5B8",
    "latitude": 11.7415371,
    "longitude": 104.9820076,
    "operator_id": "hub-sixplus",
    "hub_name": "[Sixplus] Kandal Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Sixplus (Kandal)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "SIXPLUS INDUSTRY CO., LTD. • https://maps.app.goo.gl/dfFWQxaxuxWHaz5B8"
  },
  {
    "id": "cop-fortuna",
    "name": "Fortuna International (Cambodia) Industry Co., Ltd",
    "factory_name": "Fortuna International (Cambodia) Industry Co., Ltd",
    "short_name": "Fortuna",
    "code": "COP-FORTUNA-05",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/JFWsmQJKXA846B6s6",
    "latitude": 11.5289942,
    "longitude": 104.8547169,
    "operator_id": "hub-fortuna",
    "hub_name": "[Fortuna] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Fortuna (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Fortuna International (Cambodia) Industry Co., Ltd • https://maps.app.goo.gl/JFWsmQJKXA846B6s6"
  },
  {
    "id": "cop-kingsuccess",
    "name": "KING SUCCESS CO., LTD",
    "factory_name": "KING SUCCESS CO., LTD",
    "short_name": "King Success",
    "code": "COP-KINGSUCC-10",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/nxM9M1VG9wipMcTH7",
    "latitude": 11.4552078,
    "longitude": 104.991836,
    "operator_id": "hub-kingsuccess",
    "hub_name": "[King Success] Kandal Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ King Success (Kandal)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "KING SUCCESS CO., LTD • https://maps.app.goo.gl/nxM9M1VG9wipMcTH7"
  },
  {
    "id": "cop-ocean",
    "name": "OCEAN APPAREL MANUFACTURING CO., LTD.",
    "factory_name": "OCEAN APPAREL MANUFACTURING CO., LTD.",
    "short_name": "Ocean Apparel",
    "code": "COP-OCEAN-15",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/8bsem3Vx9y4ysauD8",
    "latitude": 11.5292663,
    "longitude": 104.793456,
    "operator_id": "hub-ocean",
    "hub_name": "[Ocean Apparel] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Ocean Apparel (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "OCEAN APPAREL MANUFACTURING CO., LTD. • https://maps.app.goo.gl/8bsem3Vx9y4ysauD8"
  },
  {
    "id": "cop-skyworth",
    "name": "Skyworth Fashion(Cambodia) Co., Ltd",
    "factory_name": "Skyworth Fashion(Cambodia) Co., Ltd",
    "short_name": "Skyworth",
    "code": "COP-SKYWORTH-20",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/BHnfNw2KeqY2RPuX9",
    "latitude": 11.5318879,
    "longitude": 104.8779362,
    "operator_id": "hub-skyworth",
    "hub_name": "[Skyworth] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Skyworth (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Skyworth Fashion(Cambodia) Co., Ltd • https://maps.app.goo.gl/BHnfNw2KeqY2RPuX9"
  },
  {
    "id": "cop-tfg",
    "name": "T.F.G (CAMBODIA) GARMENT CO., LTD.",
    "factory_name": "T.F.G Garment Co., Ltd.",
    "short_name": "T.F.G",
    "code": "COP-TFG-25",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Chhnang",
    "address": "https://maps.app.goo.gl/U5p7apvExhcHRZN68",
    "latitude": 11.8886181,
    "longitude": 104.7098528,
    "operator_id": "hub-tfg",
    "hub_name": "[T.F.G] Kampong Chhnang Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ T.F.G (Kampong Chhnang)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "T.F.G (CAMBODIA) GARMENT CO., LTD. • https://maps.app.goo.gl/U5p7apvExhcHRZN68"
  },
  {
    "id": "cop-kkn",
    "name": "KKN Apparel Co., Ltd.",
    "factory_name": "KKN Apparel Co., Ltd.",
    "short_name": "KKN Apparel",
    "code": "COP-KKN-11",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Koh Kong",
    "address": "https://maps.app.goo.gl/W5V6GqY1R25MpX5F8",
    "latitude": 11.6485424,
    "longitude": 102.933553,
    "operator_id": "hub-kkn",
    "hub_name": "[KKN Apparel] Koh Kong Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ KKN Apparel (Koh Kong)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "KKN Apparel Co., Ltd. • https://maps.app.goo.gl/W5V6GqY1R25MpX5F8"
  },
  {
    "id": "cop-starlight",
    "name": "Starlight Apparel Manufacturing ltd.",
    "factory_name": "Starlight Apparel Manufacturing ltd.",
    "short_name": "Starlight",
    "code": "COP-STARLIGH-21",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/TBs99m7FeiJbi4SJ6",
    "latitude": 11.6830335,
    "longitude": 105.0396844,
    "operator_id": "hub-starlight",
    "hub_name": "[Starlight] Kandal Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Starlight (Kandal)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Starlight Apparel Manufacturing ltd. • https://maps.app.goo.gl/TBs99m7FeiJbi4SJ6"
  },
  {
    "id": "cop-yakjin",
    "name": "Yakjin (Cambodia) Inc.",
    "factory_name": "Yakjin (Cambodia) Inc.",
    "short_name": "Yakjin",
    "code": "COP-YAKJIN-31",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/og6r54WjxAqe33TGA",
    "latitude": 11.5280607,
    "longitude": 104.7761474,
    "operator_id": "hub-yakjin",
    "hub_name": "[Yakjin] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Yakjin (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Yakjin (Cambodia) Inc. • https://maps.app.goo.gl/og6r54WjxAqe33TGA"
  },
  {
    "id": "cop-makalot",
    "name": "MAKALOT GARMENTS (CAMBODIA) CO., LTD.",
    "factory_name": "Makalot Garments (Cambodia) Co., Ltd. (Branch 1)",
    "short_name": "Makalot",
    "code": "COP-MAKALOT-12",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/VpprSqQEfTPfLv8h6",
    "latitude": 11.53011,
    "longitude": 104.87208,
    "operator_id": "hub-makalot",
    "hub_name": "[Makalot] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Makalot (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "MAKALOT GARMENTS (CAMBODIA) CO., LTD. • https://maps.app.goo.gl/VpprSqQEfTPfLv8h6"
  },
  {
    "id": "cop-sunhsu",
    "name": "SunHsu Garment Factory",
    "factory_name": "SunHsu Garment Factory",
    "short_name": "SunHsu",
    "code": "COP-SUNHSU-22",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Cham",
    "address": "https://maps.app.goo.gl/tP6szikGizA1J5Vq7",
    "latitude": 12.0597978,
    "longitude": 105.209486,
    "operator_id": "hub-sunhsu",
    "hub_name": "[SunHsu] Kampong Cham Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ SunHsu (Kampong Cham)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "SunHsu Garment Factory • https://maps.app.goo.gl/tP6szikGizA1J5Vq7"
  },
  {
    "id": "cop-ytc",
    "name": "YTC CORPORATION",
    "factory_name": "YTC Corporation",
    "short_name": "YTC",
    "code": "COP-YTC-32",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/B9dWFZGgEzQodtFbA",
    "latitude": 11.4734344,
    "longitude": 104.5797424,
    "operator_id": "hub-ytc",
    "hub_name": "[YTC] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ YTC (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "YTC CORPORATION • https://maps.app.goo.gl/B9dWFZGgEzQodtFbA"
  },
  {
    "id": "cop-moha",
    "name": "Moha Garments Co. Ltd.",
    "factory_name": "Moha Garments Co. Ltd.",
    "short_name": "Moha Garments",
    "code": "COP-MOHA-13",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kandal",
    "address": "https://maps.app.goo.gl/FQF1rywJfkfWr49QA",
    "latitude": 11.453196,
    "longitude": 104.8064468,
    "operator_id": "hub-moha",
    "hub_name": "[Moha Garments] Kandal Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Moha Garments (Kandal)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Moha Garments Co. Ltd. • https://maps.app.goo.gl/FQF1rywJfkfWr49QA"
  },
  {
    "id": "cop-sunfair",
    "name": "SUNFAIR GARMENT CO., LTD.",
    "factory_name": "សាន់ហ៊្វែរ ហ្គាមិន ឯ.ក",
    "short_name": "Sunfair",
    "code": "COP-SUNFAIR-23",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/YzWQcm2UhBc8QaTs8",
    "latitude": 11.4524278,
    "longitude": 104.7742024,
    "operator_id": "hub-sunfair",
    "hub_name": "[Sunfair] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Sunfair (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "SUNFAIR GARMENT CO., LTD. • https://maps.app.goo.gl/YzWQcm2UhBc8QaTs8"
  },
  {
    "id": "cop-nyankids",
    "name": "NYAN KIDS (CAMBODIA) Ltd.",
    "factory_name": "Nyan kids (cambodia) LTD",
    "short_name": "Nyan Kids",
    "code": "COP-NYANKIDS-14",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/PHXKcF3qv687CatFA",
    "latitude": 11.5216599,
    "longitude": 104.7786931,
    "operator_id": "hub-nyankids",
    "hub_name": "[Nyan Kids] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Nyan Kids (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "NYAN KIDS (CAMBODIA) Ltd. • https://maps.app.goo.gl/PHXKcF3qv687CatFA"
  },
  {
    "id": "cop-tlhandbags",
    "name": "T & L (Cambodia) Hanbags Industrial Co., Ltd.",
    "factory_name": "T & L (Cambodia) Hanbags Industrial Co., Ltd.",
    "short_name": "T&L Handbags",
    "code": "COP-TLHANDBA-24",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/dmU3LCdJba1EAGxq5",
    "latitude": 11.5390701,
    "longitude": 104.7778396,
    "operator_id": "hub-tlhandbags",
    "hub_name": "[T&L Handbags] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ T&L Handbags (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "T & L (Cambodia) Hanbags Industrial Co., Ltd. • https://maps.app.goo.gl/dmU3LCdJba1EAGxq5"
  },
  {
    "id": "cop-topsummit",
    "name": "TOP SUMMIT GARMENT INC.",
    "factory_name": "Top Summit莎美娜柬埔寨工廠",
    "short_name": "Top Summit",
    "code": "COP-TOPSUMMI-27",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/jPbYu72Tue2zFZ23A",
    "latitude": 11.5253486,
    "longitude": 104.7934172,
    "operator_id": "hub-topsummit",
    "hub_name": "[Top Summit] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Top Summit (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "TOP SUMMIT GARMENT INC. • https://maps.app.goo.gl/jPbYu72Tue2zFZ23A"
  },
  {
    "id": "cop-trax",
    "name": "TRAX APPAREL (CAMBODIA) CO., LTD.",
    "factory_name": "ក្រុមហ៊ុន​ ត្រាកស៏ អាប់ភើរែល (ខេមបូឌា)",
    "short_name": "Trax Apparel",
    "code": "COP-TRAX-28",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/ZEnjGqHi73HZ5Bnb6",
    "latitude": 11.5613297,
    "longitude": 104.8756385,
    "operator_id": "hub-trax",
    "hub_name": "[Trax Apparel] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Trax Apparel (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "TRAX APPAREL (CAMBODIA) CO., LTD. • https://maps.app.goo.gl/ZEnjGqHi73HZ5Bnb6"
  },
  {
    "id": "cop-wanheda",
    "name": "Wan He Da Manufacturing Company Limited",
    "factory_name": "Wan He Da Manufacturing Company Limited",
    "short_name": "Wan He Da",
    "code": "COP-WANHEDA-29",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Kampong Speu",
    "address": "https://maps.app.goo.gl/2syua7ePP4Y7Gp766",
    "latitude": 11.5274694,
    "longitude": 104.7987984,
    "operator_id": "hub-wanheda",
    "hub_name": "[Wan He Da] Kampong Speu Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Wan He Da (Kampong Speu)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Wan He Da Manufacturing Company Limited • https://maps.app.goo.gl/2syua7ePP4Y7Gp766"
  },
  {
    "id": "cop-hongsone",
    "name": "Hongs One (Cambodia) Garment Co., Ltd.",
    "factory_name": "Hongs One (Cambodia) Garment Co., Ltd.",
    "short_name": "Hongs One",
    "code": "COP-HONGSONE-06",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/hbFRJb63rdP9tssAA",
    "latitude": 11.5216358,
    "longitude": 104.8592455,
    "operator_id": "hub-hongsone",
    "hub_name": "[Hongs One] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ Hongs One (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "Hongs One (Cambodia) Garment Co., Ltd. • https://maps.app.goo.gl/hbFRJb63rdP9tssAA"
  },
  {
    "id": "cop-xotex",
    "name": "XO TEX Industrial Co.,Ltd",
    "factory_name": "XO TEX Industrial Co.,Ltd 联泰",
    "short_name": "XO TEX",
    "code": "COP-XOTEX-30",
    "industry": "Garments & Textiles",
    "category": "Garment & Apparel Manufacturing",
    "tier": "VIP Platinum Partner",
    "discount_rate": "15% Corporate Off",
    "payment_terms": "Net 30 Days",
    "credit_limit": 50000,
    "current_balance": 0,
    "province": "Phnom Penh",
    "address": "https://maps.app.goo.gl/sE6hoX4r3W2zBq6A8",
    "latitude": 11.5282947,
    "longitude": 104.8646301,
    "operator_id": "hub-xotex",
    "hub_name": "[XO TEX] Phnom Penh Logistics Hub",
    "primary_corridor": "Top Sports HQ ⇄ XO TEX (Phnom Penh)",
    "rating": 5,
    "total_waybills": 0,
    "total_tonnage": 0,
    "total_spend": 0,
    "cod_collected": 0,
    "status": "active",
    "notes": "XO TEX Industrial Co.,Ltd • https://maps.app.goo.gl/sE6hoX4r3W2zBq6A8"
  }
];
